apiVersion: v1
kind: Service
metadata:
  name: zabbix-amp-agent-service
  namespace: monitoring
spec:
  ports:
  - port: 10050
    targetPort: zabbix-port
    protocol: TCP
    name: zabbix-agent
  selector:
    app: zabbix-amp-agent