apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-up-amp-agent-confmap
  namespace: monitoring
data:
  userparameteters.conf : |-
    UserParameter=amp.query[*],bash /usr/lib/zabbix/externalscripts/amp.sh $1 $2