apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-amp-agent
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-amp-agent
  template:
    metadata:
      labels:
        app: zabbix-amp-agent
    spec:
      nodeSelector:
        karpenter.sh/provisioner-name: general
      serviceAccountName: amp-iamproxy-query-service-account
      containers:
      - name: awssigv4
        image: pablommr/aws-sigv4-proxy:v1.8
        ports:
        - containerPort: 8080
          name: awssigv4-port
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
      - name: zabbix-amp-agent
        image: zabbix/zabbix-agent:6.4.14-centos
        ports:
        - containerPort: 10050
          name: zabbix-port
        resources:
          limits:
            cpu: 130m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        envFrom:
        - configMapRef:
            name: zabbix-agent-confmap
        volumeMounts:
        - name: external-scripts
          mountPath: /usr/lib/zabbix/externalscripts
        - name: user-parameter
          mountPath: /etc/zabbix/zabbix_agentd.d
      volumes:
      - name: external-scripts
        configMap:
          name: zabbix-amp-agent-confmap
      - name: user-parameter
        configMap:
          name: zabbix-up-amp-agent-confmap