services:
  db:
    image: mysql:8.0.36
    container_name: mysql
    hostname: mysql
    command: ["--character-set-server=utf8", "--collation-server=utf8_bin"]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: 123456
    ports:
       - "3306:3306"
  zabbix-server:
    image: zabbix/zabbix-server-mysql:7.0.0-centos
    container_name: zabbix-server
    hostname: zabbix-server
    restart: always
    depends_on:
      - db
    links:
      - db
    environment:
      DB_SERVER_HOST: "db"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "123456"
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:7.0.0-centos
    container_name: zabbix-web
    hostname: zabbix-web
    restart: always
    depends_on:
      - zabbix-server
    links:
      - db
    environment:
      DB_SERVER_HOST: "db"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "123456"
      ZBX_SERVER_HOST: "zabbix-server"
    ports:
      - "8080:8080"
  zabbix-agent:
    image: zabbix/zabbix-agent:7.0.0-centos
    container_name: zabbix-agent
    hostname: zabbix-agent
    restart: always
    depends_on:
      - zabbix-server
    links:
      - zabbix-server
    environment:
      ZBX_HOSTNAME: "Zabbix Server"
      ZBX_SERVER_HOST: "zabbix-server"