apiVersion: v1
kind: Service
metadata:
  name: zabbix-proxy-service
  namespace: monitoring
spec:
  ports:
  - port: 10051
    targetPort: zabbix-port
    protocol: TCP
    name: zabbix-proxy
  - port: 10050
    targetPort: zabbix-agent
    protocol: TCP
    name: zabbix-agent
  selector:
    app: zabbix-proxy