apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zabbix-proxy
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: zabbix-proxy
  serviceName: "zabbix-proxy"
  replicas: 1
  template:
    metadata:
      annotations:
        karpenter.sh/do-not-disrupt: "true"
      labels:
        app: zabbix-proxy
    spec:
      nodeSelector:
        karpenter.sh/provisioner-name: general
      containers:
      - name: zabbix-proxy
        image: zabbix/zabbix-proxy-mysql:7.0.0-centos
        ports:
        - containerPort: 10051
          name: zabbix-port
        envFrom:
        - configMapRef:
            name: zabbix-proxy-confmap
        - secretRef:
            name: zabbix-secret
      - name: zabbix-agent
        image: zabbix/zabbix-agent:7.0.0-centos
        ports:
        - containerPort: 10050
          name: zabbix-agent
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        env:
          - name: ZBX_HOSTNAME
            value: zabbix-proxy
          - name: ZBX_SERVER_HOST
            value: zabbix-proxy-service
          - name: ZBX_PASSIVESERVERS
            value: 127.0.0.1