apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-proxy-confmap
  namespace: monitoring
data:
  DB_SERVER_HOST: "mysql-service"
  MYSQL_USER: "zabbix"
  MYSQL_DATABASE: "zabbix_proxy"
  ZBX_DEBUGLEVEL: "2"
  ZBX_PROXYMODE: "0"
  ZBX_HOSTNAME: "zabbix-proxy-core"
  ZBX_SERVER_HOST: "zabbix-server-service"