apiVersion: v1
kind: Service
metadata:
  name: zabbix-web-service
  namespace: monitoring
spec:
  ports:
  - port: 8080
    targetPort: zabbix-port
    protocol: TCP
    name: zabbix-web
  selector:
    app: zabbix-web