apiVersion: v1
kind: Service
metadata:
  name: zabbix-server-service
  namespace: monitoring
spec:
  ports:
  - port: 10051
    targetPort: zabbix-port
    protocol: TCP
    name: zabbix-server
  selector:
    app: zabbix-server